# Generated by Django 5.1.2 on 2024-10-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('AttorneyID', models.AutoField(primary_key=True, serialize=False)),
                ('AttorneyName', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('YearsOfExperience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('StatusID', models.AutoField(primary_key=True, serialize=False)),
                ('StatusDescription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('ClientID', models.AutoField(primary_key=True, serialize=False)),
                ('ClientName', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('CourtID', models.AutoField(primary_key=True, serialize=False)),
                ('CourtName', models.CharField(max_length=70)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('SpecializationID', models.AutoField(primary_key=True, serialize=False)),
                ('TypeSpecialization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('AssistantID', models.AutoField(primary_key=True, serialize=False)),
                ('AssistantName', models.CharField(max_length=70)),
                ('Email', models.EmailField(max_length=50)),
                ('Phone', models.CharField(max_length=11)),
                ('Attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.attorney')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('CaseID', models.AutoField(primary_key=True, serialize=False)),
                ('CaseType', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.attorney')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.casestatus')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.client')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.attorney')),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.case')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('DocumentID', models.AutoField(primary_key=True, serialize=False)),
                ('FileName', models.CharField(max_length=150)),
                ('UploadDate', models.DateField()),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.case')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('InvoiceID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IssueDate', models.DateField()),
                ('DueDate', models.DateField()),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.case')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.client')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('JudgeID', models.AutoField(primary_key=True, serialize=False)),
                ('JudgeName', models.CharField(max_length=70)),
                ('YearsOfExperience', models.IntegerField()),
                ('Court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.court')),
            ],
        ),
        migrations.CreateModel(
            name='CaseCourt',
            fields=[
                ('CaseCourtID', models.AutoField(primary_key=True, serialize=False)),
                ('HearingDate', models.DateField()),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.case')),
                ('Court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.court')),
                ('Judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.judge')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentID', models.AutoField(primary_key=True, serialize=False)),
                ('PaymentDate', models.DateField()),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PaymentMethod', models.CharField(max_length=50)),
                ('Invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Precedent',
            fields=[
                ('PrecedentID', models.AutoField(primary_key=True, serialize=False)),
                ('PrecedentDescription', models.CharField(max_length=150)),
                ('Case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.case')),
            ],
        ),
        migrations.CreateModel(
            name='AttorneySpecialization',
            fields=[
                ('AttorneySpecializationID', models.AutoField(primary_key=True, serialize=False)),
                ('Attorney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.attorney')),
                ('Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LawCompany.specialization')),
            ],
        ),
    ]
